language: node_js
node_js:
- '10'
- '12'
- '13'
after_script:
- lerna run build
- lerna run example
after_success:
- npx codecov
after_failure:
- npx codecov
deploy:
  provider: npm
  email: npm@t-code.pl
  edge: true
  api_key:
    secure: IXdoPGyh5Y3xZPhdcKv5rmKcLyP5vItoo8iFNqI0U5Gd5k+q+LKZ6TGXLI0EGl3rfEEs1M+8Q+tsj2MpZWlCbpBHjXRRokqG7Hk62OeH4tr+TQCKcKJtI995BblxRm83wVBFexoidO/ibDPQ65UY38fSpVrNTxpt/SCd2lXVpLnmYGuNwdlCcCuu3CLcdaVuExnh/D/NSUn63jNmCWeHKSpeGs4/qj1Hqz9fQKYzx7F1m7BTPf1fooa6IwHekGW2R4WdxYuPFVt9cfMvbziHyVYpdmN9U+ZRJ7XGy19eh4Z4yc0JLhLnOXAl+PFk+6R2mRm1WHU68f0qqPxtkOpxHRWlcK1Xt+TEveG6fsG4TjKX5/OLMSJDF7BW6IqLOJ4ushkMcD1cQWh+XPQ37Zstn13Ibu51HNNv5h6y7WARe7ZEOgMDxA9ydyJDkV1qnIt3vxEwrhfZyUGMAnZoyi+2lONUVWKtS9RSlOS/8eN0/JbwJnjkLejn5sNV85O1t6lqVE5y+DzXmVbBszfb1pqbkDW2arn1ODkOU2kVa1EtuP5zjOThGz1w/zmF5HxE/TzDnDFRrTILStcrsDg6586PyGiep2Zls6hHmblAdBwv4QS/hDvH+PPMOHhvRgf8kpr6PCgDvpAhNvZ/P0grrfOpqENB5zOcnVp4osoE5tMywCE=
  on:
    tags: true
    repo: tpluscode/rdfine
    node: '13'
